name: Build Dumanwu APK

on:
  push:
    paths:
      - 'src/zh/dumanwu/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew :src:zh:dumanwu:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: dumanwu-apk
          path: src/zh/dumanwu/build/outputs/apk/debug/dumanwu-debug.apk